### ISSUE TITLE
Streaming output support

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#101]
## Is your feature request related to a problem? Please describe.

Text generation will require supporting modules that return `DataStream[T]` to stream output.
This will need to be hooked up to a unary-stream RPC.

## Describe the solution you'd like

Tasks can specify `DataStream[T]` as output type

Service generation code adds output streaming flag in py-to-proto

Servicer implementation returns something like...
```
stream = model.run
return iter(stream.map(stream_class.to_proto()))
```

## Additional context

Add any other context about the feature request here.

**Comment by evaline-ju** [comment]
Some decisions from caikit architecture club:
- A task that will require streams will be a separate task
     - A default stream block implementation _could_ batch a non-stream block's responses. This can be task implementation specific.
- This will mainly affect the `module.run` functions
- We will remove the `module.stream` function.
- We will be keeping `module.run_batch` at this time
