### ISSUE TITLE
Testing the examples in CI

### ISSUE THREAD

**Issue by afrittoli** [caikit/caikit#151]
## Is your feature request related to a problem? Please describe.

We should test the examples as part of CI to ensure that they are kept up to date with the latest changes to caikit so that the project always provides a great experience for newcomers trying out caikit. 

## Describe the solution you'd like

A CI job that runs all the examples under https://github.com/caikit/caikit/tree/main/examples

## Describe alternatives you've considered

The alternative today is to ask PR authors and reviewers to check the examples manually.
It could be added to the PR template as a checkbox to remind contributors about it.

## Additional context

See the issue solved in #145

**Comment by markstur** [comment]
Also see #184
