### ISSUE TITLE
Fix `test_train_job_works_with_wait`

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#16]
## Describe the bug

Flaky test- we sometimes get a ConfigParser object has no attribute training error

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: 3.9
- Library version: ???

## Sample Code

`tox -e 3.9`

## Expected behavior

tests should all pass

## Observed behavior

that test fails, don't have a stack trace atm

**Comment by thefirebanks** [comment]
Is this... still an existing test? Couldn't find it in the repo 😮

**Comment by evaline-ju** [comment]
@thefirebanks good point - I'm thinking it was what became [`test_run_train_job_works_with_wait`](https://github.com/caikit/caikit/blob/ea3b1bbd3f9bea5beea250a6e2e37e89ed0d2e1a/tests/runtime/servicers/test_global_train_servicer_impl.py#L235) but I also haven't seen it be a problem recently in recent builds.

@joerunde thoughts on closing this as unneeded?
