### ISSUE TITLE
Pure python rest gateway

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#18]
## Description

As an author of a caikit library, I want to have a REST interface available without any extra work.

## Discussion

Currently we use the grpc gateway wrapper to provide rest support. This is problematic because:
- It requires a custom build process using `go` to pull the proto interfaces from the library, generate a gateway, and place it in a container image with configuration carefully wired up 
- Using `go` in a build process widens the vulnerability service of the final runtime image
- grpc-gateway supports swagger v2 but we would really like openapi v3 support

We have the expertise available both for openapi and protobuf/grpc to write our own rest gateway layer in the runtime. This would allow us to support REST out of the box in python, with no extra build process or `go` required.

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by gabe-l-hart** [comment]
Closing since we've introduced native HTTP support
