### ISSUE TITLE
Migrate from GabeStyle to Google Style docstrings

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#180]
## Is your feature request related to a problem? Please describe.

Our docstrings are mostly in @gabe-l-hart style, which is close to but not quite the Google docstring format. We would like to migrate to the Google docstring format so that tools like Sphinx can understand the docstrings and create good user-facing resources. We would also like this style to be enforced going forward, so that nothing ends up documented in a different style.

## Describe the solution you'd like

All docstrings are in Google format

## Describe alternatives you've considered

Other formats? But once we're in Google format there are public tools available to migrate between them.

## Additional context

This will probably require a custom conversion script, nobody should be doing this by hand.

As a bonus, we could consider requiring docstrings on all "public" functions (things that don't start with `_`)

**Comment by joerunde** [comment]
@WillMJ https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html

**Comment by afrittoli** [comment]
We could use something like the `docstrings` plugin for `flake8`, it supports the Google format of docstring, e.g.

```
➜ flake8 --docstring-convention google | grep ': D'
./__init__.py:16:1: D200 One-line docstring should fit on one line with quotes
./base.py:16:1: D200 One-line docstring should fit on one line with quotes
./base.py:70:1: D202 No blank lines allowed after function docstring
./base.py:70:1: D205 1 blank line required between summary line and description
./base.py:70:1: D415 First line should end with a period, question mark, or exclamation point
./base.py:156:1: D202 No blank lines allowed after function docstring
./base.py:156:1: D205 1 blank line required between summary line and description
./base.py:156:1: D415 First line should end with a period, question mark, or exclamation point
./base.py:289:1: D415 First line should end with a period, question mark, or exclamation point
./base.py:341:1: D202 No blank lines allowed after function docstring
(...)
```

Once the check is in place, we can start addressing the different style rules one at the time and enforce them in the `flake8` config.

**Comment by afrittoli** [comment]
See #186 too.

**Comment by sboagibm** [comment]
@joerunde said:
> As a bonus, we could consider requiring docstrings on all "public" functions (things that don't start with _)

I think this is too prescriptive, and not practical.  For some very public interfaces, like `run` on blocks, an enforcement mechanism makes sense.
