### ISSUE TITLE
[P0] Configure job publish pypi for Open Data Hub

### ISSUE THREAD

**Issue by heyselbi** [caikit/caikit#254]

**Comment by joerunde** [comment]
Hey @heyselbi, do you have any more context on this issue? Do you have more requirements on top of our current pypi publication job?

**Comment by hickeyma** [comment]
@heyselbi Why the `[PO]` prefix in the title?

**Comment by danielezonca** [comment]
> Hey @heyselbi, do you have any more context on this issue? Do you have more requirements on top of our current pypi publication job?

I think current pypi publication job should be already good, this ticket is part of the list of activities that we need to check/do to onboard CAIKit into OpenData Hub. In this case is more a checkbox to verify but I expect no action is necessary.

Btw we decided to fork the project and create similar tickets directly there (https://github.com/opendatahub-io/caikit) to avoid spamming here :)
(i.e. we will probably configure some additional analyser job on the codebase)

> @heyselbi Why the `[PO]` prefix in the title?

`[P0]` is just a classification/prioritisation that we are doing, but again sorry for the spam :)

**Comment by heyselbi** [comment]
Transferring this issue to caikit's forked repo in ODH
