### ISSUE TITLE
text_sentiment example fails in v0.9.0 due to "ModuleNotFoundError: No module named 'grpc_health'"

### ISSUE THREAD

**Issue by kingaj12** [caikit/caikit#269]
## Describe the bug

The example `text_sentiment` fails with `ModuleNotFoundError: No module named 'grpc_health'`

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: Python 3.8.17
- Library version: v0.9.0

## Sample Code

`cd examples/text_sentiment && python start_runtime.py`

## Expected behavior

In `v0.7.1` (for example) the `grpc_server.main()` starts a service and writes log messages to the screen.

## Observed behavior

What you see happening (error messages, stack traces, etc...)

    $ python start_runtime.py
    Traceback (most recent call last):
      File "start_runtime.py", line 32, in <module>
        from caikit.runtime import grpc_server
      File "/home/kingaj/Github/caikit/examples/text-sentiment/.venv/lib/python3.8/site-packages/caikit/runtime/grpc_server.py", line 23, in <module>
        from grpc_health.v1 import health, health_pb2_grpc
    ModuleNotFoundError: No module named 'grpc_health'

**Comment by prashantgupta24** [comment]
Hi @kingaj12 , it should be fixed by this PR that closed minutes ago! https://github.com/caikit/caikit/pull/267

**Comment by kingaj12** [comment]
Hi @prashantgupta24 I can confirm that this works.  

Hi @evaline-ju thanks for the super fast response!!!
