### ISSUE TITLE
Refactor the "is_streaming..." logic to be RPC centric

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#285]
Currently a task class has an `is_streaming_output_task` method to determine the output-streamingess of a task. But tasks will now define unary + streaming flavors of their inputs and outputs, so the "streamingness" is now a property of each RPC that a task supports.
The `CaikitRPC` class should expose its own streamingness instead.

**Comment by prashantgupta24** [comment]
Should be fixed by https://github.com/caikit/caikit/pull/303
