### ISSUE TITLE
Create two request objects per task instead of 4

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#315]
## Is your feature request related to a problem? Please describe.

Inference tasks can support 4 flavors of streaming, unary-unary, unary-stream, stream-unary, and stream-stream.

We currently create a different protobuf request message for each of those 4, however the unary-unary and unary-stream (server streaming) request messages are identical and the stream-unary (client streaming) and stream-stream (bidi streaming)  request messages are identical. We should consolidate.

## Describe the solution you'd like

Only one request message is created for unary inputs, and one for streaming inputs.

So in short, we have:

### RPCS:
TextGenerationPredict
ClientStreamingTextGenerationPredict
ServerStreamingTextGenerationPredict
BidiStreamingTextGenerationPredict

### Messages:
TextGenerationRequest
StreamingTextGenerationRequest

## Additional context

Currently for `sample_task`, we create 3 request messages: (we don't yet implement `ClientStreaming` in `SampleTask`):
```
<class 'caikit.core.data_model.base.SampleTaskRequest'>
<class 'caikit.core.data_model.base.ServerStreamingSampleTaskRequest'>
<class 'caikit.core.data_model.base.BidiStreamingSampleTaskRequest'>
```

What we want to do is to consolidate:
```
<class 'caikit.core.data_model.base.SampleTaskRequest'>
<class 'caikit.core.data_model.base.ServerStreamingSampleTaskRequest'>
``` 
to a single request message called `SampleTaskRequest`

Also rename the bidi streaming task request 
```
<class 'caikit.core.data_model.base.BidiStreamingSampleTaskRequest'>
```
to `StreamingSampleTaskRequest`

**Comment by evaline-ju** [comment]
In offline discussions I believe this won't be worked on?

**Comment by gabe-l-hart** [comment]
Closing as wontfix for now
