### ISSUE TITLE
http-server in the example/text-sentiment returns "Model ... not loaded" 

### ISSUE THREAD

**Issue by kingaj12** [caikit/caikit#323]
## Describe the bug

I am experimenting with the new http_server (thanks @gabe-l-hart!) by replacing the `grpc_server.main()` call in the text-sentiment example server `examples/text-sentiment/start_runtime.py`.

The api from the swagger interface `127.0.0.1:8080/docs` asks for a `model_id`.  I have tried the `module_id` from the file `examples/text-sentiment/models/text_sentiment/config.yml` and also the `module_id` from the `caikit_huggingface_demo/example_models/sentiment/config.yml`.  I also just tried putting in random integers and strings.  But the server reports model not loaded.  

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: Python 3.11.4
- Library version: main

## Sample Code

Replace `grpc_server.main()` with `http_server.main()` in the line 
https://github.com/caikit/caikit/blob/5644440249c30bc62aede294bde1860b703e58f6/examples/text-sentiment/start_runtime.py#L41

## Expected behavior

Executing the curl command with the id from the text-sentiment config file should return `200`
```
curl -X 'POST' \
  'http://127.0.0.1:8080/api/v1/8f72161-c0e4-49b0-8fd0-7587b3017a35/task/hugging-face-sentiment' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "inputs": {
    "text_input": {
      "text": "I am happy!"
    }
  }
}'

```
## Observed behavior
The curl command returns

```

{
    "details": "Model '8f72161-c0e4-49b0-8fd0-7587b3017a35' not loaded", 
    "code": 404, 
    "id": "68a6c0fb0cc24e6b89be0c6cfa4d6eb4"
}

```

## Additional context

I guess it's not really clear to me what `model_id` is asking for.

**Comment by kingaj12** [comment]
It looks like the `model_id` expected is `text_sentiment`.   But now there is another issue:
```

curl -X 'POST' \
  'http://127.0.0.1:8080/api/v1/text_sentiment/task/hugging-face-sentiment' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "inputs": {
    "text_input": {
      "text": "I am happy"
    }
  }
}'
```
returns a Null response:
```

{
  "classes": [
    {
      "class_name": null,
      "confidence": null
    }
  ]
}
```

**Comment by kingaj12** [comment]
Further debugging shows that the `run` method in `text_sentiment.runtime_model.hf_module.HuggingFaceSentimentModule` is being called and the correct raw results are obtained there:

`{'label': 'POSITIVE', 'score': 0.9998801946640015}`

But these are not returned properly to the `GlobalPredictServicer.predict_model` method.

**Comment by gabe-l-hart** [comment]
Thanks for the debugging @kingaj12! cc @prashantgupta24 @aluu317 @joerunde

**Comment by kingaj12** [comment]
I don't know if this is relevant, but grpc_server and http_server take different paths through the predict_model to get the response value: the `aborter` value is assigned in the grpc_server, but is `None` in the http_server call.

**Comment by joerunde** [comment]
> the aborter value is assigned in the grpc_server, but is None in the http_server call

Yeah, that's failing as expected! We have call cancellation set up for grpc but that's still a TODO for http

**Comment by joerunde** [comment]
@kingaj12 the http server + the text sentiment example should now be working, wanna give the new examples a spin and re-open this if you run into any problems?
