### ISSUE TITLE
REST server cannot handle null in model response

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#346]
## Describe the bug

If I have a module which does not set a field in its response data model, and that field is itself a type which accepts None as a default (e.g. another data model type), then response serialization fails in the rest server.

## Platform

- Interpreter version: 3.11
- Library version: 0.11.0

## Sample Code

The simplest thing to do is not set a `ProducerId` where a DM output has one specified

## Expected behavior

Either a `{producer_id: null}` or a `{producer_id: {name: "", version: ""}}` would probably be acceptable.

## Observed behavior

We get a cryptic error from uvicorn with not much help:

> {"channel": "uvicorn.error", "exception": "Traceback (most recent call last):
\n File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
\n result = await app( # type: ignore[func-returns-value]
\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\n File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in call
\n return await self.app(scope, receive, send)
\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
\n File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in call
\n await super().call(scope, receive, send)
\n File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in call
\n await self.middleware_stack(scope, receive, send)
\n File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in call
\n raise exc
\n File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in call
\n await self.app(scope, receive, _send)
\n File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in call
\n raise exc
\n File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in call
\n await self.app(scope, receive, sender)
\n File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in call
\n raise e
\n File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in call
\n await self.app(scope, receive, send)
\n File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in call
\n await route.handle(scope, receive, send)
\n File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
\n await self.app(scope, receive, send)
\n File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
\n response = await func(request)
\n ^^^^^^^^^^^^^^^^^^^
\n File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
\n content = await serialize_response(
    \n ^^^^^^^^^^^^^^^^^^^^^^^^^
\n File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 154, in serialize_response
\n raise ResponseValidationError(
    \nfastapi.exceptions.ResponseValidationError", "level": "error", "message": "Exception in ASGI application
\n", "num_indent": 0, "thread_id": 281473881595936, "timestamp": "2023-07-20T18:16:14.088814"}
{"channel": "uvicorn.access", "exception": null, "level": "info", "message": "172.17.0.1:47910 - "POST /api/v1/foo/task/text-generation HTTP/1.1" 500", "num_indent": 0, "thread_id": 281473881595936, "timestamp": "2023-07-20T18:16:14.278682"}

**Comment by prashantgupta24** [comment]
I'm able to replicate this with a unit test, changing the `OtherOutputType` to have `producer_id`:
```
@dataobject(package="caikit_data_model.sample_lib")
class OtherOutputType(DataObjectBase):
    """A simple return type for the `other_task` task"""

    farewell: str
    producer_id: ProducerId
```
and not changing the `run` signature for `OtherModule`:
```
    def run(
        self, sample_input: Union[SampleInputType, str]
    ) -> Union[OtherOutputType, str]:
        return OtherOutputType(f"goodbye: {sample_input.name} {self.batch_size} times")
```

**Comment by prashantgupta24** [comment]
One thing to note - adding `Optional` to the DM type makes it work

This works:
```
@dataobject(package="caikit_data_model.sample_lib")
class OtherOutputType(DataObjectBase):
    """A simple return type for the `other_task` task"""

    farewell: str
    producer_id: Optional[ProducerId]
```

**Comment by prashantgupta24** [comment]
So the root cause of the issue (putting it here mostly for my understanding) is that we have a `pydantic model` created for the `response` of the `OtherOutputType` module, which _expects_ a `string` along with a `producer_id`. If the response from the module doesn't provide either of those fields, it results in a validation error on the `pydantic model` as it expects all fields to be present.

I'm not sure if that's incorrect? If the `module` doesn't provide all mandatory return type fields, shouldn't we error out?

**Comment by joerunde** [comment]
@prashantgupta24 🤔  yeah, that all tracks. It's different than how grpc works by dumping out zero values for everything unset, and maybe that's a good thing?

What we should probably do here then is:
1. Make the `producer_id` field optional in any interfaces currently in `caikit.interfaces`
2. See if we can enable any better error message from the response validation. Trying to debug this with no information at all is super duper not fun :(

**Comment by prashantgupta24** [comment]
Yep that seems reasonable!
