### ISSUE TITLE
Make services more configurable at runtime and dump-time

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#387]
## Is your feature request related to a problem? Please describe.

placeholder:
@gabe-l-hart has some deets

## Additional context

Add any other context about the feature request here.

**Comment by evaline-ju** [comment]
How does https://github.com/caikit/caikit/issues/380 differ?

**Comment by joerunde** [comment]
I think #380 is the simple on/off flag for grpc and http interfaces

I think what @gabe-l-hart was talking about is a more fine-grained configuration like turning specific services (inference, training + training mgmt, model-runtime) on and off, or even going deeper and disabling specific training algorithms if you don't have a trainer that supports them

**Comment by joerunde** [comment]
(plus maybe we refactor a bit of the file generation so that we can stick all the proto defs from the same package into one file, etc.)
