### ISSUE TITLE
Detect newly Unsupported models in current service generation

### ISSUE THREAD

**Issue by aluu317** [caikit/caikit#424]
## What are we implementing?
We need a way to detect any regression in module support, specifically in `ServicePackageFactory.get_service_package` ([link](https://github.com/caikit/caikit/blob/main/caikit/runtime/service_factory.py#L93)). So we can notify at generation time that this API could potentially break backwards compatibility. 

An example:

If the previous API supports modules:
```
sample_task.sample_implementation.SampleModule
other_task.other_implementation.OtherModule
```

And the current API being generated will now only support:

```
other_task.other_implementation.OtherModule
```

This needs a failure in assertion for backwards compatibility that this will be an API breaking change. 

## How are we implementing this?
We will implement this via:
- a new config group in `config.yml`, specifically in `service_generation` [group](https://github.com/caikit/caikit/blob/main/caikit/config/config.yml#L133) to enable backwards compatibility check. And a config for file path to a `modules.json` that has the included and excluded modules from a previous version that we are checking compatibility for
- `get_service_package` to use the information from config above, as well as the modules to be included/excluded in this current generation to detect any regressed support for modules, throw an error if breaking changes is detected, and alert for new module support.
- `[dump_services.py](https://github.com/caikit/caikit/blob/main/caikit/runtime/dump_services.py)` should also output a `modules.json` file so we can see a list of included modules and excluded modules.

## How will users of caikit runtime use this?
For libraries that need to use this feature will need to supply:
- in `config.yml`, enable the backwards compatibility check and a file path to the previous version of `modules.json` to check against (see above)

## What this PR does NOT do:
It checks against a list of supported modules, it does not check module list per task.

**Comment by prashantgupta24** [comment]
Great idea! Some questions that I have:

1. Where will this `modules.json` be saved? Will it be saved in GH repos for now? What about when we release docker images? How will a user pass in an older `modules.json` file then?
2. I'm assuming this will be an optional config if we don't want to check for backward compatibility?

**Comment by aluu317** [comment]
@prashantgupta24 Ah good questions!
1. I'm thinking that from caikit point of view, `modules.json` will be a `.gitignore` file and only gets generated if someone runs `dump_services` or the example script, like https://github.com/caikit/caikit/blob/main/examples/sample_lib/start_runtime_with_sample_lib.py (similar to how `protos` dir is generated in that script). 

    From a library point of view, they would have to pull `modules.json` from a previous version docker image and pass the path of that file in `config.yml` (see below example).

2. Yes, the config to do backwards compatibility is optional, should be enabled by a flag. 
Example of config would be like:
```
runtime:
    service_generation:
        check_backwards_compatibility:
            enabled: true
            prev_version_modules_file_path: /prev_modules.json
            generated_modules_file_path: /modules.json
```
If not specified, it's not enabled by default.

**Comment by prashantgupta24** [comment]
> pull modules.json from a previous version docker image and pass the path of that file in config.yml (see below example), and package modules.json as part of their release image

Yeah this was causing us trouble in our internal pipeline as well :(
