### ISSUE TITLE
🐛 Data model objects with bytes don't round trip to/from json

### ISSUE THREAD

**Issue by gabe-l-hart** [caikit/caikit#460]
## Describe the bug

A data model instance, when loaded from its `json` representation should match the original object. If the object contains a `bytes` field, this does not happen due to the bytes being `base64` serialized in [to_json](https://github.com/caikit/caikit/blob/main/caikit/core/data_model/base.py#L935) but not in [from_json](https://github.com/caikit/caikit/blob/main/caikit/core/data_model/base.py#L741).

## Sample Code

```py
from caikit.core.data_model import dataobject, DataObjectBase

@dataobject
class Foo(DataObjectBase):
    foo: bytes

f = Foo("asdf")
f2 = Foo.from_json(f.to_json())
# This fails!
assert f.foo == f2.foo
```

## Expected behavior

`f.foo == f2.foo` should be `True`

**Comment by prashantgupta24** [comment]
@gabe-l-hart Based on recent discussions, is this bug irrelevant? If the intention is to `reject attempts to set fields with the wrong type`, then ideally
```
f = Foo("asdf")
```
is incorrect
```
f = Foo(b"asdf")
```
and using this works as expected?

**Comment by prashantgupta24** [comment]
And ideally we should open a separate issue in which we explicitly `reject attempts to set fields with the wrong type`?
