### ISSUE TITLE
Union of return types throws an exception

### ISSUE THREAD

**Issue by prashantgupta24** [caikit/caikit#47]
## Describe the bug

If I have a run function defined like this:
```
def run(self, sample_input: SampleInputType) -> Union[OtherOutputType, str]:
```
I get an exception:
```
AttributeError: '_SpecialForm' object has no attribute 'get_proto_class'
```

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: 3.9
- Library version: 0.1.3

## Sample Code

Another example:
```
  def run(self, sample_input: SampleInputType) -> str:
```
gives me:
```
AttributeError: type object 'str' has no attribute 'get_proto_class'
```
**Note: This has been deemed invalid since we do not want to support return of primitive types through modules.**

## Expected behavior

The introspection logic should iterate through the `Union` defined and pick the `data model` type from it.

## Observed behavior

```
self = typing.Union[sample_lib.data_model.sample.OtherOutputType, str], attr = 'get_proto_class'

    def __getattr__(self, attr):
        # We are careful for copy and pickle.
        # Also for simplicity we don't relay any dunder names
        if '__origin__' in self.__dict__ and not _is_dunder(attr):
>           return getattr(self.__origin__, attr)
E           AttributeError: '_SpecialForm' object has no attribute 'get_proto_class'
```

## Additional context

While returning the `return_type` from `serializers.py`, we should perhaps call the `py_type_to_proto_type` method (that existed before) to pick the `data model` from the `Union` type - or think about reusing some code from it!

**Comment by joerunde** [comment]
@prashantgupta24 we should definitely _not_ call `py_type_to_proto_type`! All the conversions to proto types are now handled by `@dataobject` instead. We're trying to get the introspection bits down to worrying about python types only.

Sounds good re: picking the data model type out of a union, though users would need to be very careful about models that can potentially return non-data-model things, since those will 🤮 if invoked via the runtime

**Comment by prashantgupta24** [comment]
@joerunde yep definitely not the full function as is, but a lot of code is reusable!
