### ISSUE TITLE
Allow third-party implementations for data sources

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#517]
## Is your feature request related to a problem? Please describe.

We've made some assumptions in caikit that for places where data locations are described in our APIs, like `DataStreamSource` parameters or the `output_path` top-level training api parameter, either files will simply exist on disk or an s3 blob is "good enough" to locate the data.

However, for security-minded applications, this requires that a consuming application be responsible for securely fetching user data and providing it to caikit. This:
- may be onerous in the context of a distributed application where services that need data are always responsible for fetching it themselves
- may not meet security requirements if the user data has to land on disk for caikit to read

## Describe the solution you'd like

Similar to how caikit allows third-party implementations of `trainers` `finders` and `initializers`, we think an abstraction for data sources may be necessary. This would allow users of caikit to plug in their own data fetching implementation to meet their own security requirements.

## Additional context

This may affect the generated service APIs?????

**Comment by gabe-l-hart** [comment]
This has been completed with the addition of Output Target in #546
