### ISSUE TITLE
RUN44773514E obscures true cause of runtime startup failure

### ISSUE THREAD

**Issue by ssiegel95** [caikit/caikit#545]
## Is your feature request related to a problem? Please describe.

Consider the following environment configuration:

```sh
env:
  - name: RUNTIME_LAZY_LOAD_LOCAL_MODELS
     value: "TRUE"
    - name: RUNTIME_TRAINING_SAVE_WITH_ID
     value: "FALSE"
   - name: RUNTIME_TRAINING_OUTPUT_DIR
     value: "models"
   - name: RUNTIME_LOCAL_MODELS_DIR
     value: "/app/models"
```

This will lead to the following being printed as the last line of the stack:

```
  File "/usr/local/lib/python3.10/site-packages/caikit/core/exceptions/error_handler.py", line 384, in value_check
    self(
  File "/usr/local/lib/python3.10/site-packages/caikit/core/exceptions/error_handler.py", line 130, in log_raise
    raise exception
ValueError: value check failed: Must set runtime.local_models_dir with runtime.lazy_load_local_models
```

This is a confusing message because the user has specified both `RUNTIME_LOCAL_MODELS_DIR` and `RUNTIME_LAZY_LOAD_LOCAL_MODELS`. The actual cause of the failure is that the value for the former (`/app/models`) doesn't exist and it needs to if `RUNTIME_LAZY_LOAD_LOCAL_MODELS` is set to true. The user does see 

```{"channel": "MODEL-MANAGR", "exception": null, "level": "warning", "log_code": "<RUN53709826W>", "message": "Invalid runtime.local_models_dir /app/models. Does not exist", "num_indent": 0, "thread_id": 140593866667840, "timestamp": "2023-10-26T15:21:46.223266"}``` in the log file but seeing RUN44773514E as the final entry obscures the fact that the above warning is actually fatal.

## Describe the solution you'd like

Clearer error or warning messaging about the requirement that `RUNTIME_LOCAL_MODELS_DIR` needs to be present.

**Comment by waleedqk** [comment]
Is the required solution here that the error message should be more expressive, signifying that the `_local_models_dir` while set, is not a valid dir path?

**Comment by ssiegel95** [comment]
Yes, seeing `"Invalid runtime.local_models_dir /app/models. Does not exist"` as the terminal message in the stack instead of `ValueError: value check failed: Must set runtime.local_models_dir with runtime.lazy_load_local_models` would making resolution for the user much easier. At least it would have for me as I missed the first message in the flood of log messages and focused my attention on the latter.

**Comment by waleedqk** [comment]
Thank you for the feedback
Can you review https://github.com/caikit/caikit/pull/591 when you get a chance to see if addresses the issue
