### ISSUE TITLE
IBM AfroHacks at AfroTech Participation 

### ISSUE THREAD

**Issue by jritten** [caikit/caikit#550]
IBM AfroHacks at AfroTech Hackathon starts on Monday, and the Caikit project repo(s) are not properly labeled to indicate to participants wanting to contribute to Caikit during the 2-day hackathon which projects/issues to work on.

Add “afrohacks” to Settings => Topics on any Caikit repos, and add "afrohacks" to issue Labels, to indicate the repos/repo issues Caikit would like to have participants work on during the 48-hour AfroHacks at AfroTech Hackathon starting on Monday. Please feel free to connect with me with any questions. Thank you!

**Comment by jritten** [comment]
https://ibm.biz/afrohacks-hackathon

**Comment by gabe-l-hart** [comment]
Added for now and will plan to remove them once the hackathon completes
