### ISSUE TITLE
Provide a repository template

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#64]
## Description

As an ai model author, I want to spin up a new project with caikit, so that I can wrap my models in caikit interfaces to load in my applications

## Discussion

@gkumbhat has some experience setting up slick repo templates.

We can probably get one going that does any boilerplatey stuff, though we should try to remove as much as possible.

Should we include docker image support to build an image that boots the runtime?

## Acceptance Criteria

- [ ] A template repo exists that users can quickly hack on to get a caikit project running

**Comment by hickeyma** [comment]
Closing as covered by #70
