### ISSUE TITLE
Provide a huggingface template + examples

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#67]
## Is your feature request related to a problem? Please describe.

Huggingface has loads of ai models ready to download and use. We should make the on-ramp to consuming them via caikit as simple as possible.

## Describe the solution you'd like

A repo that has support for a couple types of huggingface models, with bootstrap functionality to stand up caikit model artifacts with one line in the interpreter.

## Describe alternatives you've considered

???

**Comment by hickeyma** [comment]
Closing as covered by #70
