### ISSUE TITLE
Quickstart/docs for model users

### ISSUE THREAD

**Issue by joerunde** [caikit/caikit#68]
## Description

As a user of ML models, I want to know the steps to bootstrapping or loading a model with caikit, so that I can onboard my supported models to caikit and run them

## Discussion

This will require some template / example repos to exist. See #64 and #67

We should cover at least the bootstrap/load and local run case, maybe we can leave the whole "how do I deploy this model in Fargate / Code Engine / Openshift" for later 😉 

## Acceptance Criteria

- [ ] READMEs are updated

**Comment by hickeyma** [comment]
Closing as covered by #70
