### ISSUE TITLE
Support oneofs/Union[int, str, ...] in function signatures

### ISSUE THREAD

**Issue by prashantgupta24** [caikit/caikit#7]
## Is your feature request related to a problem? Please describe.

Running the `training` introspection on a funtion that has `Union[int, str]` of 2 primitive types results in an error:
```
def train(cls, time_column: Union[int, str] = None):
```
output:
```
E           ValueError: Invalid input schema: typing.Union[int, str]
```

## Describe the solution you'd like

For a function signature like this:
```
def train(cls, time_column: Union[int, str] = None):
```

The introspection should ideally create a `oneof` with the 2 fields:
```
oneof time_column {
        int64 ts_int     = 1;
        string ts_str   = 2;
    } 
```

**Comment by evaline-ju** [comment]
Will be supported with [py-to-proto](https://pypi.org/project/py-to-proto/) integration
