### ISSUE TITLE
[bug] _get_request_params is being called twice in http server's unary input unary output handler

### ISSUE THREAD

**Issue by tozhangkai** [caikit/caikit#728]
## Is your feature request related to a problem? Please describe.

I happened to find the Caikit calls into my data model code twice when processing an http request. When digging into the code I see there's duplicate calls to `self._get_request_params(rpc, request)` in the unary input unary output handler:

https://github.com/caikit/caikit/blob/4abc7babbe16461810d4ffdd14eb1c2760c89dac/caikit/runtime/http_server/http_server.py#L608 

and

https://github.com/caikit/caikit/blob/4abc7babbe16461810d4ffdd14eb1c2760c89dac/caikit/runtime/http_server/http_server.py#L618

## Describe the solution you'd like

Remove the duplicate calls

**Comment by gabe-l-hart** [comment]
@tozhangkai Thanks for finding the bug and the quick fix! Your fix is rolling out with `caikit==0.26.28`

**Comment by tozhangkai** [comment]
Thanks for the speedy review @gabe-l-hart!
