### ISSUE TITLE
Can we not E0503...os_error:"No such file or directory all the time?  Is it just me?

### ISSUE THREAD

**Issue by markstur** [caikit/caikit#92]
## Describe the bug

I get an error, but I don't think it's a real error.

E0503 17:25:08.082902000 140704599909184 chttp2_server.cc:1045]        UNKNOWN:No address added out of total 1 resolved for 'unix:///tmp/mmesh/grpc.sock' {created_time:"2023-05-03T17:25:08.082045-07:00", children:[UNKNOWN:Unable to configure socket {fd:6, created_time:"2023-05-03T17:25:08.080064-07:00", children:[UNKNOWN:No such file or directory {created_time:"2023-05-03T17:25:08.078961-07:00", errno:2, os_error:"No such file or directory", syscall:"bind"}]}]}

I'm looking for cleaner output for demo, but really logging this as a bug because bogus but serious looking error message can cause everybody that has trouble getting started to have to deal with triage of this one.

Unless it is just me.  Then what might I be doing wrong?

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: 3.9
- Library version: 0.2.0

## Sample Code

from caikit.runtime import grpc_server
grpc_server.main()

## Expected behavior

Library users should not see bogus errors that look like real errors.  These get in the way every time someone has to troubleshoot something.

## Observed behavior

see above

**Comment by joerunde** [comment]
@markstur shootin from the hip but I think #93 should fix it?

**Comment by markstur** [comment]
That's good shootin' @joerunde 

I did a quick test by hacking in that `if` and it works.  Thanks!
